add audio sticker
getsince/test3 pull request #695
Opened 2022-04-14 01:02 UTC by akhrail1996

2022-04-14 01:13 UTC, akhrail1996 commented on lib/t_web/channels/user_socket.ex
> +  defp check_version(version), do: Version.match?(version, ">= 6.0.0")
discontinuing support of older versions, the majority of users are on 6+ already

2022-04-14 01:13 UTC, akhrail1996 commented on lib/t_web/views/view_helpers.ex
> -      # users on version < 6.0.0 don't support private pages
no longer needed

2022-04-14 09:48 UTC, ruslandoga commented on lib/t_web/views/view_helpers.ex
>          if Map.has_key?(label, "text-contact") do
text-contact need to be deleted

2022-04-14 09:49 UTC, ruslandoga commented on lib/t_web/views/view_helpers.ex
> +          case process_label(label, version) do
not clear why `process_*` function can return `nil`

2022-04-14 09:49 UTC, ruslandoga commented on lib/t_web/views/view_helpers.ex
> +  defp process_label(%{"s3_key" => key} = label, version) do
bad idea

2022-04-14 09:51 UTC, ruslandoga commented on test/t_web/views/view_helpers_test.exs
> +              "B7UZsWtPLtbgYg1SRenEdP154VNLVXTQMaQUQkoh55hSCimnEGIIIcSUUkwhhJBSjDGGHINOOqYUckophJQC"
why is waveform a string?

2022-04-14 10:01 UTC, ruslandoga commented on lib/t_web/views/view_helpers.ex
> +  defp process_label(%{"question" => "telegram", "answer" => handle} = label, _version) do
process_label shouldn't have `_version` if it's being ignored in every but one function clause

2022-04-14 10:04 UTC, ruslandoga requested changes
Please split audio stickers PR from other unrelated changes. In general, adding and removing functionality in the same deploy-cycle is "forbidden" in a clustered environment where different nodes can run different versions at the same time since it can affect their ability to cooperate.

1. add new functionality (audio)
2. deploy, enable new functionality
3. wait for changes to propagate through the cluster
4. remove old functionality (if necessary)
5. deploy

2022-04-14 11:11 UTC, ruslandoga approved these changes

2022-04-14 15:56 UTC, akhrail1996 commented
feeling proud of the praise from my maestro
![video-to-gif-converter](https://user-images.githubusercontent.com/16062322/163427714-b647d276-52e4-4724-9531-853421985d12.gif)

your recommendations make total sense, I will follow them, thanks!

2022-04-14 17:13 UTC, ruslandoga commented on lib/t/accounts.ex
> +      acl: "private"
It might need to be `public` unless we add signing to each audio asset.

2022-04-14 17:15 UTC, ruslandoga commented on lib/t_web/views/view_helpers.ex
> +  defp s3_key_image_url(key, width) when is_binary(key) do
it returns a map, not a single url, that was the reason behind `urls` in the name

2022-04-14 17:17 UTC, ruslandoga commented on lib/t_web/views/view_helpers.ex
> +        %{"s3_key" => key, "waveform" => _w} = label, acc ->
or `question = audio` can also be used as an identifier

2022-04-14 17:18 UTC, ruslandoga commented on lib/t_web/views/view_helpers.ex
> +        %{"s3_key" => key, "waveform" => _w} = label, acc ->
I'd prefer the processing to happen once, in process_labels_v6()

2022-04-14 17:20 UTC, ruslandoga commented on lib/t/accounts.ex
> +    Media.user_presigned_url(s3_key)
I see it's presigned, but it probably doesn't have to be since the asset is "public".

2022-04-14 17:25 UTC, ruslandoga commented on test/t_web/views/view_helpers_test.exs
> +    #  "X-Amz-Signature=ba7b862afdded85fc8f4c647d59f375d90a71d4f1faa9b872214b869556cd4de"
are these urls cached correctly on ios?

2022-04-14 17:27 UTC, akhrail1996 commented on test/t_web/views/view_helpers_test.exs
> +    #  "X-Amz-Signature=ba7b862afdded85fc8f4c647d59f375d90a71d4f1faa9b872214b869556cd4de"
yes: 'Current.documentDirectory.appendingPathComponent(s3Key + ".m4a")'

2022-04-14 18:30 UTC, ruslandoga commented on lib/t/accounts.ex
> +    Media.user_s3_url(s3_key)
these audio files should probably be distributed via cloudfront

2022-04-14 18:31 UTC, ruslandoga commented on lib/t_web/views/view_helpers.ex
> +              case Version.compare(version, "6.2.0") do
version check can be done once

2022-04-14 18:31 UTC, ruslandoga commented on test/t_web/views/view_helpers_test.exs
> +    # audio url looks like:
then the `URI.parse` workaround for `assert` is unnecessary

2022-04-15 06:23 UTC, ruslandoga commented on lib/t/media.ex
> +    IO.puts(url)
should probably be removed

2022-04-15 06:24 UTC, ruslandoga commented on lib/t/media.ex
> +    Path.join([static_cdn_endpoint(), Base.url_encode64(url, padding: false)])
what is this for? static cdn != user cdn

2022-04-15 06:27 UTC, ruslandoga approved these changes

2022-04-15 14:24 UTC, merged